//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class clienteventasEntities : DbContext
    {
        public clienteventasEntities()
            : base("name=clienteventasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
    
        public virtual int ps_agregarcli(Nullable<decimal> id, string nom, string apell, string email, Nullable<decimal> precioper, Nullable<decimal> nroP, Nullable<decimal> total)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(decimal));
    
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apellParameter = apell != null ?
                new ObjectParameter("apell", apell) :
                new ObjectParameter("apell", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var precioperParameter = precioper.HasValue ?
                new ObjectParameter("precioper", precioper) :
                new ObjectParameter("precioper", typeof(decimal));
    
            var nroPParameter = nroP.HasValue ?
                new ObjectParameter("nroP", nroP) :
                new ObjectParameter("nroP", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ps_agregarcli", idParameter, nomParameter, apellParameter, emailParameter, precioperParameter, nroPParameter, totalParameter);
        }
    
        public virtual int ps_eliminar(Nullable<decimal> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ps_eliminar", iParameter);
        }
    }
}
